### ISSUE TITLE
tui2: "local variable 'width' referenced before assignment"

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-tui#26]
```$ tui2









Traceback (most recent call last):
  File "/Users/jwr003/repos/gems-qa-auto/venv/bin/tui2", line 33, in <module>
    sys.exit(load_entry_point('pytest-tui', 'console_scripts', 'tui2')())
  File "/Users/jwr003/coding/pytest-tui/pytest_tui/tui2.py", line 129, in main
    tui.create_test_result_tabs()
  File "/Users/jwr003/coding/pytest-tui/pytest_tui/tui2.py", line 81, in create_test_result_tabs
    results_splitter.addWidget(results_list, width)
UnboundLocalError: local variable 'width' referenced before assignment
```

**Comment by jeffwright13** [comment]
Cannot reproduce anymore.
