### ISSUE TITLE
Handle launch of `tuihtml` script when output_html.html does not exist

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-tui#43]
```
$ tuihtml

Traceback (most recent call last):
  File "/Users/jwr003/repos/gems-qa-auto/venv/bin/tuihtml", line 8, in <module>
    sys.exit(main())
  File "/Users/jwr003/repos/gems-qa-auto/venv/lib/python3.9/site-packages/pytest_tui/html.py", line 63, in main
    (mode, ino, dev, nlink, uid, gid, size, atime, mtime, ctime) = os.stat(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jwr003/repos/gems-qa-auto/gems_qa_tests/results/output_html.html'
```

**Comment by jeffwright13** [comment]
Done
