### ISSUE TITLE
No per-test results when run with --emoji-out

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-tui#8]
`$ pytest --fold --emoji-out --ft=t`

yields:
<img width="1498" alt="Screen Shot 2022-04-06 at 1 17 31 PM" src="https://user-images.githubusercontent.com/4308435/162051820-86078548-0452-49a5-8290-0c2e28f11ad9.png">

**Comment by jeffwright13** [comment]
Still an issue in v0.9.0.

When run, output is:
```
Traceback (most recent call last):
  File "/Users/jwr003/coding/pytest-tui/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 188, in console_main
    code = main()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 165, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/_pytest/main.py", line 310, in wrap_session
    config._ensure_unconfigure()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 997, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/plugin.py", line 222, in pytest_unconfigure
    pytui_tui(config)
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/plugin.py", line 239, in pytui_tui
    tuitk()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/tui_pytermtk.py", line 119, in main
    tui.create_test_result_tabs()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/tui_pytermtk.py", line 71, in create_test_result_tabs
    results_splitter.addWidget(results_list, width)
UnboundLocalError: local variable 'width' referenced before assignment
```

**Comment by jeffwright13** [comment]
Or when run with `tui` only:
```
Traceback (most recent call last):
  File "/Users/jwr003/coding/pytest-tui/venv/bin/tui1", line 8, in <module>
    sys.exit(main())
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/tui_pytermtk.py", line 119, in main
    tui.create_test_result_tabs()
  File "/Users/jwr003/coding/pytest-tui/venv/lib/python3.9/site-packages/pytest_tui/tui_pytermtk.py", line 71, in create_test_result_tabs
    results_splitter.addWidget(results_list, width)
UnboundLocalError: local variable 'width' referenced before assignment
```

**Comment by jeffwright13** [comment]
This plugin is not supported.
