### ISSUE TITLE
html_gen exception if no user env var JAVA_HOME

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-tui#94]
$ python /Users/jwr003/coding/pt2/pytest_tui/html_gen.py

Traceback (most recent call last):
  File "/Users/jwr003/coding/pt2/pytest_tui/html_gen.py", line 372, in <module>
    main()
  File "/Users/jwr003/coding/pt2/pytest_tui/html_gen.py", line 354, in main
    html_tabs = page.create_tabs()
                ^^^^^^^^^^^^^^^^^^
  File "/Users/jwr003/coding/pt2/pytest_tui/html_gen.py", line 275, in create_tabs
    tab_metadata = f"""<div id="{TAB_METADATA[0]}" class="tabcontent"> <p>{self.get_metadata()}</p> </div>"""
                                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jwr003/coding/pt2/pytest_tui/html_gen.py", line 317, in get_metadata
    m.pop("JAVA_HOME")
KeyError: 'JAVA_HOME'

**Comment by jeffwright13** [comment]
Fixed in 1.7.2.
