### ISSUE TITLE
UnboundLocalError: local variable 'HTML_OUTPUT_FILE' referenced before assignment

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-tui#95]
```$ tuih
Traceback (most recent call last):
  File "/Users/jwr003/repos/gqa/venv/bin/tuih", line 8, in <module>
    sys.exit(main())
  File "/Users/jwr003/repos/gqa/venv/lib/python3.9/site-packages/pytest_tui/html_gen.py", line 360, in main
    with open(HTML_OUTPUT_FILE, "w+") as f:
UnboundLocalError: local variable 'HTML_OUTPUT_FILE' referenced before assignment```

**Comment by jeffwright13** [comment]
Unable to reproduce, but added safeguard code (making HTML_REPORT_FILE global) to make sure. Commit 707853a..0e7f5d4.
